### ISSUE TITLE
Install on MacOS 

### ISSUE THREAD

**Issue by LovellHAGSC** [russcd/Ancestry_HMM#11] opened 2021-06-08 01:32 UTC
Hi there,
Thanks for your work on this. 
I have been using Ancestry_HMM for a while now with great success. But, after updating my OS, I am unable to use the previously installed version. I'm sure this is something on my end, but I can't figure out how to resolve it. 
I am running Armadillo 10.5.1 on MacOS 11.2.3 (BigSur). I. wonder if it is as simple as downgrading back to an older version of Armadillo. If thats the case, what version would you suggest? 
Any advice is much appreciated. 
John

If I call my old install:
```
$ /Ancestry_HMM/src/ancestry_hmm -h
dyld: Library not loaded: /usr/local/opt/armadillo/lib/libarmadillo.9.dylib
  Referenced from: /Users/jlovell/Desktop/popGen/Ancestry_HMM/src/ancestry_hmm
  Reason: image not found
zsh: abort      /Ancestry_HMM/src/ancestry_hmm -h
```

If I try to make:
```
src % make 
c++     -O3 -o ancestry_hmm ancestry_hmm.cpp -larmadillo
In file included from ancestry_hmm.cpp:22:
In file included from /usr/local/include/armadillo:21:
/usr/local/include/armadillo_bits/compiler_check.hpp:50:4: error: "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
  #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   ^
In file included from ancestry_hmm.cpp:22:
In file included from /usr/local/include/armadillo:29:
```

**Comment by russcd** [comment] 2021-06-08 02:06
Hallo! 

I am glad you've found Ancestry_HMM useful! I think this is actually a pretty easy fix. *famous last words*

I think that all you need to do is call your compiler with "-std=c++11". If you get back into the /src directory and try this:

`c++ -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp -larmadillo `

I expect it will work. If not, you may also need to also link the armadillo library. e.g., for a homebrew installation of armadillo this works for me: 

`c++ -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp -L /opt/homebrew/Cellar/armadillo/10.5.1/lib -I /opt/homebrew/Cellar/armadillo/10.5.1/include -larmadillo`

I hope that helps and please let me know if that doesn't solve the problem.

**Comment by LovellHAGSC** [comment] 2021-06-08 03:09
hmm. That didn't do it, and help on the various errors haven't proved informative. Also just did a fresh developer tools and armadillo install.  
Same errors when linking armadillo directly. Do you see an obvious solution? If not, maybe I'll try it though the conda method.
Thanks.
John

```
src % c++ -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp
In file included from ancestry_hmm.cpp:22:
In file included from /usr/local/include/armadillo:29:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
```

etc.

**Comment by russcd** [comment] 2021-06-08 16:57
I'm closing this for now. In case others find a similar error, the problem is very likely related to having two cmath.h header files per this stackoverflow post: https://stackoverflow.com/questions/58628377/catalina-c-using-cmath-headers-yield-error-no-member-named-signbit-in-th

**Closed as completed by russcd** 2021-06-08 16:58 UTC

**Comment by apfuentes** [comment] 2022-03-08 14:53
Hi @russcd,

Thanks for developing this package. This is the first time that I try to use it, and I am having problems to compile it in my laptop (MacOS v. 11.6.4, BigSur, 16GB RAM). I wonder if maybe you could help me figure out what the problem is.

I followed these steps:

1. Install `armadillo` and `gperftools` using Conda:
```
cd ~/miniconda3/envs/balsfjord-env
# activate conda environment created for AHMM and AHMM-S
conda activate balsfjord-env

# Install dependencies
conda install -c conda-forge armadillo
conda install -c conda-forge gperftools
```
Confirm the libraries were created. In `/lib` directory:
```
~/miniconda3/envs/balsfjord-env/lib$ ls
total 77M
drwxr-xr-x 3 USERNAME staff   96 Mar  8 10:51 clang/
drwxr-xr-x 5 USERNAME staff  160 Mar  8 10:51 cmake/
-rwxrwxr-x 2 USERNAME staff 399K Feb  1 16:21 libarmadillo.10.8.2.dylib*
lrwxr-xr-x 1 USERNAME staff   25 Mar  8 10:51 libarmadillo.10.dylib -> libarmadillo.10.8.2.dylib*
lrwxr-xr-x 1 USERNAME staff   25 Mar  8 10:51 libarmadillo.dylib -> libarmadillo.10.8.2.dylib*
-rwxrwxr-x 2 USERNAME staff 344K Feb 25  2021 libarpack.2.1.0.dylib*
lrwxr-xr-x 1 USERNAME staff   21 Mar  8 10:51 libarpack.2.dylib -> libarpack.2.1.0.dylib*
-rw-rw-r-- 2 USERNAME staff 491K Feb 25  2021 libarpack.a
lrwxr-xr-x 1 USERNAME staff   21 Mar  8 10:51 libarpack.dylib -> libarpack.2.1.0.dylib*
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 libblas.3.dylib -> libopenblasp-r0.3.18.dylib*
-rw-rw-r-- 2 USERNAME staff 137K May 25  2021 libblas.a
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 libblas.dylib -> libopenblasp-r0.3.18.dylib*
-rwxrwxr-x 2 USERNAME staff 833K Dec 30 09:19 libc++.1.0.dylib*
lrwxr-xr-x 1 USERNAME staff   16 Mar  8 10:51 libc++.1.dylib -> libc++.1.0.dylib*
-rw-rw-r-- 2 USERNAME staff 1.2M Dec 30 09:18 libc++.a
lrwxr-xr-x 1 USERNAME staff   16 Mar  8 10:51 libc++.dylib -> libc++.1.0.dylib*
-rw-rw-r-- 2 USERNAME staff 7.8K Dec 30 09:18 libc++experimental.a
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 libcblas.3.dylib -> libopenblasp-r0.3.18.dylib*
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 libcblas.dylib -> libopenblasp-r0.3.18.dylib*
-rw-rw-r-- 1 USERNAME staff 145K Mar  8 10:51 libgcc_s.1.dylib
lrwxr-xr-x 1 USERNAME staff   16 Mar  8 10:51 libgcc_s_ppc64.1.dylib -> libgcc_s.1.dylib
lrwxr-xr-x 1 USERNAME staff   16 Mar  8 10:51 libgcc_s_x86_64.1.dylib -> libgcc_s.1.dylib
-rwxrwxr-x 1 USERNAME staff 6.2M Mar  8 10:51 libgfortran.5.dylib*
lrwxr-xr-x 1 USERNAME staff   19 Mar  8 10:51 libgfortran.dylib -> libgfortran.5.dylib*
lrwxr-xr-x 1 USERNAME staff   12 Mar  8 10:51 libgomp.1.dylib -> libomp.dylib*
lrwxr-xr-x 1 USERNAME staff   12 Mar  8 10:51 libgomp.dylib -> libomp.dylib*
lrwxr-xr-x 1 USERNAME staff   12 Mar  8 10:51 libiomp5.dylib -> libomp.dylib*
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 liblapack.3.dylib -> libopenblasp-r0.3.18.dylib*
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 liblapack.dylib -> libopenblasp-r0.3.18.dylib*
-rwxrwxr-x 2 USERNAME staff 734K Mar  3 23:16 libomp.dylib*
lrwxr-xr-x 1 USERNAME staff   26 Mar  8 10:51 libopenblas.0.dylib -> libopenblasp-r0.3.18.dylib*
-rwxrwxr-x 2 USERNAME staff  63M Oct  3 23:58 libopenblasp-r0.3.18.dylib*
-rwxrwxr-x 2 USERNAME staff  55K Feb 10 19:34 libprofiler.0.dylib*
-rw-rw-r-- 2 USERNAME staff  76K Feb 10 19:34 libprofiler.a
lrwxr-xr-x 1 USERNAME staff   19 Mar  8 12:04 libprofiler.dylib -> libprofiler.0.dylib*
-rwxrwxr-x 1 USERNAME staff 296K Mar  8 10:51 libquadmath.0.dylib*
lrwxr-xr-x 1 USERNAME staff   19 Mar  8 10:51 libquadmath.dylib -> libquadmath.0.dylib*
-rw-rw-r-- 2 USERNAME staff 813K May 25  2021 libsuperlu.a
-rwxrwxr-x 2 USERNAME staff 243K Feb 10 19:34 libtcmalloc.4.dylib*
-rw-rw-r-- 2 USERNAME staff 387K Feb 10 19:34 libtcmalloc.a
lrwxr-xr-x 1 USERNAME staff   19 Mar  8 12:04 libtcmalloc.dylib -> libtcmalloc.4.dylib*
-rwxrwxr-x 2 USERNAME staff 261K Feb 10 19:34 libtcmalloc_and_profiler.4.dylib*
-rw-rw-r-- 2 USERNAME staff 429K Feb 10 19:34 libtcmalloc_and_profiler.a
lrwxr-xr-x 1 USERNAME staff   32 Mar  8 12:04 libtcmalloc_and_profiler.dylib -> libtcmalloc_and_profiler.4.dylib*
-rwxrwxr-x 2 USERNAME staff 166K Feb 10 19:34 libtcmalloc_minimal.4.dylib*
-rw-rw-r-- 2 USERNAME staff 256K Feb 10 19:34 libtcmalloc_minimal.a
lrwxr-xr-x 1 USERNAME staff   27 Mar  8 12:04 libtcmalloc_minimal.dylib -> libtcmalloc_minimal.4.dylib*
drwxr-xr-x 6 USERNAME staff  192 Mar  8 12:04 perl5/
drwxr-xr-x 9 USERNAME staff  288 Mar  8 12:04 pkgconfig/
```
In `/include` directory:
```
~/miniconda3/envs/balsfjord-env/include$ ls
total 252K
-rw-rw-r--   2 USERNAME staff  30K Jun 16  2016 armadillo
drwxr-xr-x 598 USERNAME staff  19K Mar  8 10:51 armadillo_bits/
drwxr-xr-x  11 USERNAME staff  352 Mar  8 10:51 arpack/
drwxr-xr-x   3 USERNAME staff   96 Mar  8 10:51 c++/
drwxr-xr-x  11 USERNAME staff  352 Mar  8 12:04 google/
drwxr-xr-x  12 USERNAME staff  384 Mar  8 12:04 gperftools/
-rw-rw-r--   2 USERNAME staff  48K Mar  3 23:16 omp-tools.h
-rw-rw-r--   2 USERNAME staff  23K Mar  3 23:16 omp.h
-rw-rw-r--   2 USERNAME staff  48K Mar  3 23:16 ompt.h
-rw-rw-r--   2 USERNAME staff  11K Oct 18  2020 slu_Cnames.h
-rw-rw-r--   2 USERNAME staff  12K Oct 18  2020 slu_cdefs.h
-rw-rw-r--   2 USERNAME staff 2.3K Oct 18  2020 slu_dcomplex.h
-rw-rw-r--   2 USERNAME staff  12K Oct 18  2020 slu_ddefs.h
-rw-rw-r--   2 USERNAME staff 2.2K Oct 18  2020 slu_scomplex.h
-rw-rw-r--   2 USERNAME staff  12K Oct 18  2020 slu_sdefs.h
-rw-rw-r--   2 USERNAME staff  16K Oct 18  2020 slu_util.h
-rw-rw-r--   2 USERNAME staff  13K Oct 18  2020 slu_zdefs.h
-rw-rw-r--   2 USERNAME staff 3.6K Oct 18  2020 superlu_enum_consts.h
-rw-rw-r--   2 USERNAME staff 7.9K Oct 18  2020 supermatrix.h
```

2. Link the conda-based installation of `armadillo` and `tcmalloc` for compilation by providing the path to these libraries in the `Makefile`. For this, I followed the recommendation in https://github.com/russcd/Ancestry_HMM/blob/master/src/Makefile, and added `--std=c++11`, as recommended to @LovellHAGSC.

The `Makefile` looks like this (see  March 8, 2022 line):
```
##  A MAKEFILE FOR The Ancestry HMM. TO USE, RUN THE COMMAND "make" VIA COMMAND LINE ##

TCFLAGS = -ltcmalloc 
ARMAFLAGS = -larmadillo

all:
#	$(LINK.cc) -O3 -o ancestry_hmm ancestry_hmm.cpp $(ARMAFLAGS)
### if tcmalloc is installed, this can be linked using the command below instead
#	$(LINK.cc) -O3 -o ancestry_hmm ancestry_hmm.cpp $(TCFLAGS) $(ARMAFLAGS)

## if you have a local armadillo installation, you will need to provide the directory during compile time and possible also link lblas and lapack 
## our recommendation is to use miniconda3 to do the installation
##	$ conda install -c conda-forge armadillo
## then you will have the appropriate lib and include files in your home directory under subdirectory miniconda3/
## so, replace USERNAME with your unix id on the following line and try this

       #$(LINK.cc) -O3 -o ancestry_hmm ancestry_hmm.cpp -L /home/USERNAME/miniconda3/lib/ -I /home/USERNAME/miniconda3/include/ $(ARMAFLAGS)

## (March 8, 2022) if you have a local armadillo and tcmalloc installation, use:
	$(LINK.cc) -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp -L /Users/USERNAME/miniconda3/envs/balsfjord-env/lib/ -I /Users/USERNAME/miniconda3/envs/balsfjord-env/include/ $(TCFLAGS) $(ARMAFLAGS)

## if it builds correctly, you will also need to link the library during runtime
## to do this, add the following line to your ~/.bash_profile or ~/.bashrc
##     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/USERNAME/miniconda3/lib/
```
3. Compile the program:
```
~/Tools/Ancestry_HMM/src$ make
```
No messages were displayed in the screen.

4. Link the library path for runtime:
```
nano ~/.bash_profile

# Add this line
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Users/USERNAME/miniconda3/envs/balsfjord-env/lib/
```
5. Run the program:
```
~/Tools/Ancestry_HMM/src$ ./ancestry_hmm -h
dyld: Library not loaded: @rpath/libtcmalloc.4.dylib
  Referenced from: /Users/USERNAME/Tools/Ancestry_HMM/src/./ancestry_hmm
  Reason: image not found
Abort trap: 6
```

Thanks for any help!

**Comment by russcd** [comment] 2022-03-08 15:31
Looks like a linking error. Two things to try:

1. Can you remove the tcmalloc link from the compile instruction $(TCFLAGS). 
2. Can you try adding  `export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/Users/USERNAME/miniconda3/envs/balsfjord-env/lib/` to your bash profile?

**Comment by apfuentes** [comment] 2022-03-08 16:51
Hey, the recommended changes worked!

I followed these steps:

Delete $(TCFLAGS) from the `Makefile`:
```
$(LINK.cc) -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp -L /Users/USERNAME/miniconda3/envs/balsfjord-env/lib/ -I /Users/USERNAME/miniconda3/envs/balsfjord-env/include/ $(ARMAFLAGS)
```
Run `make`:
```
~/Tools/Ancestry_HMM/src$ make
c++     -O3 --std=c++11 -o ancestry_hmm ancestry_hmm.cpp -L /Users/angfu103/miniconda3/envs/balsfjord-env/lib/ -I /Users/angfu103/miniconda3/envs/balsfjord-env/include/ -larmadillo
```
Add this line to the bash profile:
```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/Users/USERNAME/miniconda3/envs/balsfjord-env/lib/ to your bash profile
```
Test the program:
```
~/Tools/Ancestry_HMM/src$ ./ancestry_hmm -h
reading command line

		ERROR: must provide input file

			-i [path/to/input_file]



ancestry_hmm usage:

	required:
		-i [string]		input file name
		-s [string]		sample id and ploidy file
		-a [int] [float] [float] ...
			number of ancestral populations and ancestry proportion attributable to each
		-p [int] [int] [float]
			ancestry pulse with format, ancestral population, time,
			and proportion of final ancestry from this pulse
			negative time or proportions indicate that parameters are to be estimated

	optional:
		--help			print this help statement
		--ne [int]		effective population size of the admixed population
		-g			samples are specified with genotypes rather than read counts
		--precision [int]	modify float and double precision to int
		-v			viterbi decoding
		-b [int] [int]		number of bootstraps and bootstrap block size in number of SNPs
		--tmax [int]		maximum time of an admixture pulse
		--tmin [int]		minimum time of an admixture pulse
		--tolerance [float]	distance in lnL units to just convergence
		-e [float]		error rates
		-E			site specific error rates are included
		--fix			ancestral allele frequencies are certain

	optional and relevant only for multiple pulse models:
		--output-ancestry	output ancestry posteriors rather than pulses
		-r [int]		number of random restarts during nelder-mead optimization
		--pmax [int]		maximum proportion ancestry in an admixture pulse
		--pmin [int]		minimum proportion ancestry in an admixture pulse
```
Thank you very much for your help!

Next, I will test the program using the "example" data file...

**Comment by russcd** [comment] 2022-03-08 18:59
Glad it worked.
